### ISSUE TITLE
Understand why SpringBatch instrumentation is not working using the OTEL agent

### ISSUE THREAD

**Issue by doppleware** [digma-ai/OpenTelemetry.Instrumentation.Digma#23]
I've been using this sample https://github.com/spring-guides/gs-batch-processing
And have been trying to use the Spring Batch instrumentation in the OTEL agent. I added the system properties described here: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/README.md But was not able to get it to work.

Can you try to troubleshoot?

**Comment by shalom938** [comment]
This app is spring-boot 3.2.0 , spring batch 5.1
otel still doesn't support spring-batch 5, they support only spring-batch 3.

https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7306

you and Arik were through it already
https://github.com/digma-ai/digma-collector-backend/issues/1199

and even for spring-batch 3 the spring-batch instrumentation is disabled by default and you need to enable it
JAVA_TOOL_OPTIONS=-Dotel.instrumentation.spring-batch.enabled=true
