### ISSUE TITLE
.NET instrumentation should use DigmaEnvironment- "digma.environment" attribute instead of deployment.environment (otel attribute)

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/OpenTelemetry.Instrumentation.Digma#8]
In order to avoid conflicts with different customer configurations, Digma should use its own deployment attribute
"digma.environment"

please note that the backend already supports it

need to issue a new version of the instrumentation and update our samples

**Comment by asafchen-dig** [comment]
Updated also:
- Otel.Sample.Application.Dotnet
- digma-services
